"""empty message

Revision ID: 18e2d8b1b6aa
Revises: 4a4973a84764
Create Date: 2015-11-01 19:06:37.632831

"""

# revision identifiers, used by Alembic.
revision = '18e2d8b1b6aa'
down_revision = '4a4973a84764'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('curricula', sa.Column('standardcurriculum_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'curricula_standardcurriculum_fkey', 'curricula', type_='foreignkey')
    op.drop_constraint(u'curricula_school_fkey', 'curricula', type_='foreignkey')
    op.create_foreign_key(None, 'curricula', 'schools', ['school_id'], ['id'])
    op.create_foreign_key(None, 'curricula', 'standardCurricula', ['standardcurriculum_id'], ['id'])
    op.drop_column('curricula', 'school')
    op.drop_column('curricula', 'standardcurriculum')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('standardcurriculum', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('curricula', sa.Column('school', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.create_foreign_key(u'curricula_school_fkey', 'curricula', 'schools', ['school'], ['id'])
    op.create_foreign_key(u'curricula_standardcurriculum_fkey', 'curricula', 'standardCurricula', ['standardcurriculum'], ['id'])
    op.drop_column('curricula', 'standardcurriculum_id')
    op.drop_column('curricula', 'school_id')
    ### end Alembic commands ###
