"""empty message

Revision ID: 2623012d2254
Revises: 18e2d8b1b6aa
Create Date: 2015-11-04 11:06:17.154143

"""

# revision identifiers, used by Alembic.
revision = '2623012d2254'
down_revision = '18e2d8b1b6aa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curricula', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('curricula', 'standardcurriculum_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('curricula', 'customization_table')
    op.drop_column('curricula', 'ordered_subtopics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('ordered_subtopics', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('curricula', sa.Column('customization_table', postgresql.JSON(), autoincrement=False, nullable=True))
    op.alter_column('curricula', 'standardcurriculum_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('curricula', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
