"""empty message

Revision ID: 351a47a9fb2f
Revises: 2623012d2254
Create Date: 2015-11-04 11:07:50.762078

"""

# revision identifiers, used by Alembic.
revision = '351a47a9fb2f'
down_revision = '2623012d2254'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('curricula', sa.Column('subtopic_id', sa.Integer(), nullable=False))
    op.add_column('curricula', sa.Column('subtopic_order', sa.Integer(), nullable=True))
    op.add_column('curricula', sa.Column('subtopic_year', sa.Integer(), nullable=True))
    op.add_column('curricula', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.add_column('curricula', sa.Column('topic_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curricula', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'curricula', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'curricula', 'subtopics', ['subtopic_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.drop_column('curricula', 'topic_order')
    op.drop_column('curricula', 'topic_id')
    op.drop_column('curricula', 'subtopic_year')
    op.drop_column('curricula', 'subtopic_order')
    op.drop_column('curricula', 'subtopic_id')
    op.drop_column('curricula', 'course_id')
    ### end Alembic commands ###
