"""empty message

Revision ID: 366e57f72b33
Revises: 3998cd42421c
Create Date: 2015-10-31 18:21:06.039557

"""

# revision identifiers, used by Alembic.
revision = '366e57f72b33'
down_revision = '3998cd42421c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('standardcurriculum_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curricula', 'standardCurricula', ['standardcurriculum_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.drop_column('curricula', 'standardcurriculum_id')
    ### end Alembic commands ###
