"""empty message

Revision ID: 3998cd42421c
Revises: 2c7d970b05ef
Create Date: 2015-10-31 18:18:36.020194

"""

# revision identifiers, used by Alembic.
revision = '3998cd42421c'
down_revision = '2c7d970b05ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'curricula_standardcurriculum_fkey', 'curricula', type_='foreignkey')
    op.drop_column('curricula', 'standardcurriculum')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('standardcurriculum', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'curricula_standardcurriculum_fkey', 'curricula', 'standardCurricula', ['standardcurriculum'], ['id'])
    ### end Alembic commands ###
