"""empty message

Revision ID: 3e6f2767dd24
Revises: 351a47a9fb2f
Create Date: 2015-11-04 16:11:45.953790

"""

# revision identifiers, used by Alembic.
revision = '3e6f2767dd24'
down_revision = '351a47a9fb2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customizedsubtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('topic_order', sa.Integer(), nullable=True),
    sa.Column('subtopic_order', sa.Integer(), nullable=True),
    sa.Column('subtopic_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'curricula_topic_id_fkey', 'curricula', type_='foreignkey')
    op.drop_constraint(u'curricula_course_id_fkey', 'curricula', type_='foreignkey')
    op.drop_constraint(u'curricula_subtopic_id_fkey', 'curricula', type_='foreignkey')
    op.drop_column(u'curricula', 'subtopic_order')
    op.drop_column(u'curricula', 'topic_order')
    op.drop_column(u'curricula', 'topic_id')
    op.drop_column(u'curricula', 'course_id')
    op.drop_column(u'curricula', 'subtopic_id')
    op.drop_column(u'curricula', 'subtopic_year')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'curricula', sa.Column('subtopic_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'curricula', sa.Column('subtopic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'curricula', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'curricula', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'curricula', sa.Column('topic_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'curricula', sa.Column('subtopic_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'curricula_subtopic_id_fkey', 'curricula', 'subtopics', ['subtopic_id'], ['id'])
    op.create_foreign_key(u'curricula_course_id_fkey', 'curricula', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(u'curricula_topic_id_fkey', 'curricula', 'topics', ['topic_id'], ['id'])
    op.drop_table('customizedsubtopics')
    ### end Alembic commands ###
