"""empty message

Revision ID: 48082c45388f
Revises: Ivo
Create Date: 2015-10-14 22:34:54.420245

"""

# revision identifiers, used by Alembic.
revision = '2015-10-14 22:34:54.420245'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_name', sa.String(length=120)))
    op.add_column('users', sa.Column('given_name', sa.String(length=50)))
    op.add_column('users', sa.Column('pw_hash', sa.String(length=600)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pw_hash')
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'family_name')
    ### end Alembic commands ###
